backend:
  repo: csmaller/rats
  name: git-gateway
media_folder: static/assets
public_folder: assets
display_url: https://www.ratsband.com
logo_url: https://www.ratsband.com/images/rats_logo.jpg
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: 'Featured Image', name: image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: 'songs'
    label: 'Songs'
    extension: 'json'

    files:
      - file: 'static/songs/songs.json'
        label: 'Song List'
        name: 'songList'
        fields:
          - name: songs
            label: songs
            widget: list
            fields:
              - { name: title }
              - { name: artist }

  - name: 'videos'
    label: 'Videos'
    extension: 'json'

    files:
      - file: 'static/videos/videos.json'
        label: 'Video List'
        name: 'videoList'
        fields:
          - name: videos
            label: videos
            widget: list
            fields:
              - { name: id }
              - { name: title }
