backend:
  name: github
  repo: csmaller/rats
  branch: main
media_folder: static/assets
public_folder: assets
display_url: https://www.ratsband.com
logo_url: https://www.ratsband.com/images/rats_logo.jpg
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Featured Image", name: image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: "songs"
    label: "Songs"
    extension: "json"
    editor:
      preview: false

    files:
    - file: "static/songs/songs.json"
      label: "Song List"
      name: "songList"
      fields:
      - name: Songs
        label: Songs
        widget: list
        fields:
        - name: songObject
          label: Song Object
          widget: list
          fields: 
          - {name: song}
          - {name: artist}
